apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: th2-mysql-volume-claim
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
