apiVersion: v1
kind: PersistentVolume
metadata:
  name: th2-mysql-volume
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/docker/Project/Personal/seminar-cnpm/mysql"
