apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
type: Opaque
data:
  s3_bucket_name: "YmRzLXByb2plY3Q="
  s3_region: "YXAtc291dGhlYXN0LTE="
  s3_api_key: "QUtJQVhSUVJTNFZWUFhSU1NPN0c="
  s3_secret: "TFpBNkRyM1VsU0FLVk50VE9qamxLL0xaWEdDcWg4NlU1NTJMb2dadA=="
  s3_domain: "ZDJhc21zMGgxNGtkMXIuY2xvdWRmcm9udC5uZXQ="
