name: th2_web
description: DSS Demo website

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  equatable: ^2.0.5
  dio: ^4.0.6
  flutter_screenutil: ^5.6.0
  shared_preferences: ^2.0.15
  flutter_svg: ^1.1.6
  google_fonts: ^3.0.1
  carousel_slider: ^4.1.1
  pretty_dio_logger: ^1.1.1
  modal_bottom_sheet: ^2.1.2
  freezed_annotation: ^1.1.0
  json_annotation: ^4.6.0
  tuple: ^2.0.1
  flutter_bloc: ^8.1.1
  intl: ^0.17.0
  clipboard: ^0.1.3
  another_flushbar: ^1.12.29
  fluttertoast: ^8.1.1
  get_it: ^7.2.0
  injectable: ^1.5.4
  cupertino_icons: ^1.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^6.0.0
  cached_network_image: ^3.2.2
  persistent_bottom_nav_bar_v2: ^4.2.6
  tab_indicator_styler: ^2.0.0

  shimmer: ^2.0.0
  logger: ^1.1.0
  flutter_lorem: ^2.0.0
  bloc_test: ^9.1.0
  go_router: ^5.1.5
  hydrated_bloc: ^9.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  injectable_generator: ^1.5.3
  build_runner: ^2.1.8
  json_serializable: ^6.3.1
  freezed: ^1.1.1
  hive_generator: ^1.1.3
  mocktail: ^0.3.0
  


flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Light.ttf
          weight: 300
        - asset: fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: fonts/Nunito-ExtraBold.ttf
          weight: 800
    - family: Ledger
      fonts:
        - asset: fonts/Ledger-Regular.ttf
    - family: SFPro
      fonts:
        - asset: fonts/SF-Pro.OTF

flutter_intl:
  enabled: true
